In [1]:
! pip install numpy

In [2]:
import numpy as np

# Numpy Data Type Practice

- Create a 1D array of integers from 1 to 5 with data type int32.

- Create a 2D array of shape (3, 3) with data type float64 where all elements are zero.

- Create a 3D array of shape (2, 2, 2) with random integers between 0 and 100 with data type int8.

- Convert a 1D array of integers to an array of floats.

- Create a 2D array of shape (2, 3) with data type float32 and then convert it to int32.


In [3]:
arr = np.arange(1,6,dtype=np.int32)
arr

array([1, 2, 3, 4, 5], dtype=int32)

In [4]:
arr = np.zeros((3, 3), dtype=np.float64)
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr = np.random.randint(0, 100, size=(2, 2, 2), dtype=np.int8)
arr

array([[[39, 86],
        [99, 65]],

       [[44, 21],
        [75, 81]]], dtype=int8)

In [6]:
arr_int = np.zeros((2,2),dtype=np.int8)
arr_int

array([[0, 0],
       [0, 0]], dtype=int8)

In [7]:
arr_float = arr_int.astype(np.float32)
arr_float

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [8]:
arr_float32 = np.array([[1.87, 2.9, 3.07], [4.5, 5.3, 6.06]], dtype=np.float32)
arr_int32 = arr_float32.astype(np.int32)
arr_int32


array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# Numpy 3-D Array Practice
- Create a 3D array of shape (4, 3, 2) with all elements initialized to zero.

- Create a 3D array of shape (2, 5, 4) with all elements initialized to one.

- Create a 3D array of shape (3, 3, 3) with random integers between 10 and 20.

In [9]:
arr = np.zeros((4, 3, 2))
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
arr = np.ones((2, 5, 4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
arr = np.random.randint(10, 20, size=(3,3,3), dtype=np.int32)
arr

array([[[17, 12, 16],
        [19, 15, 13],
        [14, 10, 19]],

       [[15, 10, 18],
        [16, 13, 10],
        [19, 15, 16]],

       [[14, 12, 15],
        [17, 14, 11],
        [17, 17, 12]]], dtype=int32)

1. Create a 3D array of dimensions 3x3x3 with all elements initialized to zero.

   ```python
   array_3d = np.zeros((3, 3, 3), dtype=int)
   ```

   Optionally, initialize with some values for practice:

   ```python
   array_3d = np.array([[[ 1,  2,  3], [ 4,  5,  6], [ 7,  8,  9]],
                        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                        [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
   ```

   Iterate over all elements in the 3D array.

In [23]:
array_3d = np.zeros((3, 3, 3), dtype=int)
array_3d

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [24]:
array_3d = np.array([[[ 1,  2,  3], [ 4,  5,  6], [ 7,  8,  9]],
                        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                        [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [13]:
for i in range(3):
    for j in range(3):
        for k in range(3):
            print(array_3d[i][j][k], end=' ')
        print(" ")
    print(" ")

1 2 3  
4 5 6  
7 8 9  
 
10 11 12  
13 14 15  
16 17 18  
 
19 20 21  
22 23 24  
25 26 27  
 


2. Create a 3D array of shape (3, 4, 5) filled with random integers between 0 and 20, and print the array.

   - Access and print the element at position (2, 3, 4) in the 3D array created above.

   - Access and print the entire first row of the second matrix (i.e., when the first-dimension index is 1).

   - Add 5 to each element in the 3D array and print the result.

   - Multiply each element in the 3D array by 2 and print the result.

   - Calculate and print the sum of all elements in the 3D array.

   - Calculate and print the mean of the elements along the second axis.

   - Create a new array containing only the elements from the original 3D array that are greater than 10.

   - Replace all elements in the 3D array that are less than 10 with the value 0 and print the modified array.

In [14]:
arr = np.random.randint(0, 20, size=(3, 4, 5), dtype=np.int32)
arr

array([[[ 7, 16,  3, 11,  9],
        [ 0,  5,  0, 17,  8],
        [ 0, 13,  8, 12,  1],
        [ 1, 19, 10,  2,  7]],

       [[ 0, 15, 12,  3,  7],
        [10,  2,  9,  4,  2],
        [ 4, 11, 18, 17,  6],
        [ 7,  1,  8,  8, 15]],

       [[ 5,  5,  5, 14,  8],
        [14, 18,  7, 18,  6],
        [ 2,  8, 17,  2, 18],
        [ 7,  1,  9, 19,  5]]], dtype=int32)

In [15]:
arr[2, 3, 4]

np.int32(5)

In [16]:
arr[1,0]

array([ 0, 15, 12,  3,  7], dtype=int32)

In [17]:
arr_add = arr + 5
arr_add

array([[[12, 21,  8, 16, 14],
        [ 5, 10,  5, 22, 13],
        [ 5, 18, 13, 17,  6],
        [ 6, 24, 15,  7, 12]],

       [[ 5, 20, 17,  8, 12],
        [15,  7, 14,  9,  7],
        [ 9, 16, 23, 22, 11],
        [12,  6, 13, 13, 20]],

       [[10, 10, 10, 19, 13],
        [19, 23, 12, 23, 11],
        [ 7, 13, 22,  7, 23],
        [12,  6, 14, 24, 10]]], dtype=int32)

In [18]:
arr_mul = arr * 2
arr_mul

array([[[14, 32,  6, 22, 18],
        [ 0, 10,  0, 34, 16],
        [ 0, 26, 16, 24,  2],
        [ 2, 38, 20,  4, 14]],

       [[ 0, 30, 24,  6, 14],
        [20,  4, 18,  8,  4],
        [ 8, 22, 36, 34, 12],
        [14,  2, 16, 16, 30]],

       [[10, 10, 10, 28, 16],
        [28, 36, 14, 36, 12],
        [ 4, 16, 34,  4, 36],
        [14,  2, 18, 38, 10]]], dtype=int32)

In [19]:
np.sum(arr)

np.int64(496)

In [20]:
print(arr.mean(axis=1))

[[ 2.   13.25  5.25 10.5   6.25]
 [ 5.25  7.25 11.75  8.    7.5 ]
 [ 7.    8.    9.5  13.25  9.25]]


In [21]:
new_array = arr[arr > 10]
new_array

array([16, 11, 17, 13, 12, 19, 15, 12, 11, 18, 17, 15, 14, 14, 18, 18, 17,
       18, 19], dtype=int32)

In [22]:
arr[arr < 10] = 0
arr

array([[[ 0, 16,  0, 11,  0],
        [ 0,  0,  0, 17,  0],
        [ 0, 13,  0, 12,  0],
        [ 0, 19, 10,  0,  0]],

       [[ 0, 15, 12,  0,  0],
        [10,  0,  0,  0,  0],
        [ 0, 11, 18, 17,  0],
        [ 0,  0,  0,  0, 15]],

       [[ 0,  0,  0, 14,  0],
        [14, 18,  0, 18,  0],
        [ 0,  0, 17,  0, 18],
        [ 0,  0,  0, 19,  0]]], dtype=int32)