In [26]:
! pip install numpy

# 2-D Array Practice

**Array Creation and Attributes**

1. Create a 4x2 integer array and print its attributes (shape, size, dimensions).

2. Create a 5x2 integer array from a range between 100 and 200, with a difference of 10 between each element.

In [27]:
import numpy as np

In [28]:
arr = np.random.rand(4,2)
arr

array([[0.39682977, 0.98895038],
       [0.23716721, 0.91114908],
       [0.32459532, 0.02982015],
       [0.52496826, 0.11938606]])

In [29]:
np.size(arr)

8

In [30]:
np.shape(arr)

(4, 2)

In [31]:
np.ndim(arr)

2

In [32]:
arr = np.arange(100, 200, 10).reshape(5, 2)
arr

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

**Array Operations**

3. Given the 2-D array `arr = numpy.array([[34,43,73],[82,22,12],[53,94,66]])`, print the maximum value from axis 0 and the minimum value from axis 1.

4. Given `sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])` and `newColumn = numpy.array([[10,10,10]])`, delete the second column from `sampleArray` and insert `newColumn` in its place.

5. For the given NumPy array `arr = np.array([[4,8,16,20], [10,20,30,40],[20,22,23,25], [30,42,53,75],[32,33,34,35]])`, print the array of odd rows and even columns.

6. Add the NumPy arrays `arr1 = np.array([[4,5,6], [7,8,9]])` and `arr2 = np.array([[2,3,4], [5,6,7]])` and calculate the cube root of the elements in the resultant matrix.

In [33]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
arr

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [34]:
arr.max(axis=0)

array([82, 94, 73])

In [35]:
arr.min(axis=1)

array([34, 12, 53])

In [36]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [37]:
newColumn = np.array([[10,10,10]])
newColumn

array([[10, 10, 10]])

In [38]:
sampleArray = np.delete(sampleArray, 1, 1)
sampleArray = np.insert(sampleArray, 1, newColumn, axis=1)
sampleArray


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [39]:
arr = np.array([[4,8,16,20], [10,20,30,40],[20,22,23,25], [30,42,53,75],[32,33,34,35]])
arr

array([[ 4,  8, 16, 20],
       [10, 20, 30, 40],
       [20, 22, 23, 25],
       [30, 42, 53, 75],
       [32, 33, 34, 35]])

In [40]:
print(arr[1::2,::2])

[[10 30]
 [30 53]]


In [41]:
arr1 = np.array([[4,5,6], [7,8,9]])
arr1

array([[4, 5, 6],
       [7, 8, 9]])

In [42]:
arr2 = np.array([[2,3,4], [5,6,7]])
arr2

array([[2, 3, 4],
       [5, 6, 7]])

In [43]:
arr3 = arr1 + arr2
arr3

array([[ 6,  8, 10],
       [12, 14, 16]])

In [44]:
arr4 = np.cbrt(arr3)
arr4

array([[1.81712059, 2.        , 2.15443469],
       [2.28942849, 2.41014226, 2.5198421 ]])

**Handling Missing Values and Data Transformation**

* How to find if a given array has any null values?
* How to replace all missing values with 0 in a NumPy array?
* How to find the count of unique values in a NumPy array?
* How to convert a numeric array to a categorical (text) array?

In [45]:
array = np.array([[1, 2, 3], [4, None, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, None, 6],
       [7, 8, 9]], dtype=object)

In [46]:
array = np.where(array == None, np.nan, array)  # Replace None
array = array.astype(float)  # Convert to float
np.isnan(array).any()

np.True_

In [47]:
array[np.isnan(array)] = 0
array

array([[1., 2., 3.],
       [4., 0., 6.],
       [7., 8., 9.]])

In [48]:
unique_values, counts = np.unique(array, return_counts=True)
unique_values

array([0., 1., 2., 3., 4., 6., 7., 8., 9.])

In [49]:
counts

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
! pip install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 56.3 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 24.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.1/41.1 MB 27.2 MB/s eta 0:00:00:00:0100:01


In [57]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
categorical_array = encoder.fit_transform(array.ravel())
print(categorical_array)

[1 2 3 4 0 5 6 7 8]


# Project: Student Grades Analysis

**Data**

We have a NumPy array `grades_data` representing student grades in different subjects over a semester. Each row represents a student, and each column represents a subject. Grades are out of 100.

grades_data = np.array([ [85, 90, 88, 72], [95, 82, 78, 88], [92, 90, 85, 88], [75, 80, 85, 90], [88, 82, 85, 92] ])

**Analysis**

* **Column-wise Calculations (axis=0):** Calculate the mean, maximum, minimum, and standard deviation of grades for each subject.
* **Row-wise Calculations (axis=1):** Calculate the mean, maximum, minimum, and standard deviation of grades for each student.
* **Total Grades:** Calculate the total grade for each student by summing their grades across all subjects.

In [56]:
grades_data = np.array([ [85, 90, 88, 72], [95, 82, 78, 88], [92, 90, 85, 88], [75, 80, 85, 90], [88, 82, 85, 92] ])
grades_data

array([[85, 90, 88, 72],
       [95, 82, 78, 88],
       [92, 90, 85, 88],
       [75, 80, 85, 90],
       [88, 82, 85, 92]])

In [58]:
np.mean(grades_data,axis=0)

array([87. , 84.8, 84.2, 86. ])

In [59]:
np.max(grades_data,axis=0)

array([95, 90, 88, 92])

In [60]:
np.min(grades_data,axis=0)

array([75, 80, 78, 72])

In [61]:
np.std(grades_data,axis=0)

array([6.89927532, 4.30813185, 3.31058907, 7.15541753])

In [63]:
np.mean(grades_data,axis=1)

array([83.75, 85.75, 88.75, 82.5 , 86.75])

In [64]:
np.max(grades_data,axis=1)

array([90, 95, 92, 90, 92])

In [65]:
np.min(grades_data,axis=1)

array([72, 78, 85, 75, 82])

In [66]:
np.std(grades_data,axis=1)

array([7.01338007, 6.41774883, 2.58602011, 5.59016994, 3.69966215])

In [67]:
np.sum(grades_data,axis=1)

array([335, 343, 355, 330, 347])