In [1]:
! pip install numpy
! pip install pandas
! pip install matplotlib

In [3]:
import numpy as np

In [4]:
arr1 = np.ones((4,5))

In [6]:
type(arr1[0][0])

numpy.float64

In [7]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])


In [8]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [9]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list, unique_values)

[ 0  2  3  4  5  6  7 12 13 14] [11 12 13 14 15 16 17 18 19 20]


In [11]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)
print(unique_values)

[3 2 2 2 1 1 1 1 1 1]
[11 12 13 14 15 16 17 18 19 20]


In [14]:
unique_values, return_inverse_item = np.unique(a,return_inverse=True)
print(a)
print(return_inverse_item)
print(unique_values)

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[0 0 1 2 3 4 5 6 1 2 0 3 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
