In [2]:
! pip install numpy

In [3]:
import numpy as np

In [4]:
arr = np.arange(1, 28).reshape(3, 3, 3).astype('int32')
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [5]:
random_arr = np.random.randint(1, 11, size=(3,3,3), dtype='int32')
random_arr

array([[[ 8,  2,  3],
        [ 1,  5,  4],
        [ 3,  7,  6]],

       [[ 6,  9,  2],
        [10,  3,  8],
        [ 5,  7,  8]],

       [[ 6,  5, 10],
        [ 8,  5,  7],
        [ 8,  4,  4]]])

In [6]:
for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [7]:
for x in np.nditer(arr, order="F"):
    print(x, end=" ")

1 10 19 4 13 22 7 16 25 2 11 20 5 14 23 8 17 26 3 12 21 6 15 24 9 18 27 

In [8]:
for x in np.nditer(arr, order="C"):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [9]:
for x in np.nditer(arr, order="A"):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [10]:
nd_arr = arr * random_arr
nd_arr.shape

(3, 3, 3)

In [12]:
nd_arr

array([[[  8,   4,   9],
        [  4,  25,  24],
        [ 21,  56,  54]],

       [[ 60,  99,  24],
        [130,  42, 120],
        [ 80, 119, 144]],

       [[114, 100, 210],
        [176, 115, 168],
        [200, 104, 108]]])

In [16]:
arr = arr.reshape(3,3,3,1)
arr

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9]]],


       [[[10],
         [11],
         [12]],

        [[13],
         [14],
         [15]],

        [[16],
         [17],
         [18]]],


       [[[19],
         [20],
         [21]],

        [[22],
         [23],
         [24]],

        [[25],
         [26],
         [27]]]])

In [19]:
new_arr = arr * random_arr
new_arr

array([[[[  8,   2,   3],
         [  2,  10,   8],
         [  9,  21,  18]],

        [[ 24,  36,   8],
         [ 50,  15,  40],
         [ 30,  42,  48]],

        [[ 42,  35,  70],
         [ 64,  40,  56],
         [ 72,  36,  36]]],


       [[[ 80,  20,  30],
         [ 11,  55,  44],
         [ 36,  84,  72]],

        [[ 78, 117,  26],
         [140,  42, 112],
         [ 75, 105, 120]],

        [[ 96,  80, 160],
         [136,  85, 119],
         [144,  72,  72]]],


       [[[152,  38,  57],
         [ 20, 100,  80],
         [ 63, 147, 126]],

        [[132, 198,  44],
         [230,  69, 184],
         [120, 168, 192]],

        [[150, 125, 250],
         [208, 130, 182],
         [216, 108, 108]]]])

In [24]:
@np.vectorize
def myfunc(a, b):
    if a > b:
        return a - b
    else:
        return a + b

In [25]:
myfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])