In [1]:
! pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 43.4 MB/s eta 0:00:0000:0100:01


In [2]:
import numpy as np

In [3]:
arr = np.arange(1, 28).reshape(3, 3, 3).astype('int32')
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)

In [4]:
random_arr = np.random.randint(1, 11, size=(3,3,3), dtype='int32')
random_arr

array([[[ 3,  1,  3],
        [ 9,  7,  9],
        [ 4,  7,  5]],

       [[ 8,  8,  8],
        [ 5,  8,  2],
        [ 6,  7,  3]],

       [[ 8,  3,  9],
        [ 8,  7,  5],
        [ 8,  4, 10]]], dtype=int32)

In [5]:
for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [6]:
for x in np.nditer(arr, order="F"):
    print(x, end=" ")

1 10 19 4 13 22 7 16 25 2 11 20 5 14 23 8 17 26 3 12 21 6 15 24 9 18 27 

In [7]:
for x in np.nditer(arr, order="C"):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [8]:
for x in np.nditer(arr, order="A"):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [9]:
nd_arr = arr * random_arr
nd_arr.shape

(3, 3, 3)

In [10]:
nd_arr

array([[[  3,   2,   9],
        [ 36,  35,  54],
        [ 28,  56,  45]],

       [[ 80,  88,  96],
        [ 65, 112,  30],
        [ 96, 119,  54]],

       [[152,  60, 189],
        [176, 161, 120],
        [200, 104, 270]]], dtype=int32)

In [11]:
arr = arr.reshape(3,3,3,1)
arr

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9]]],


       [[[10],
         [11],
         [12]],

        [[13],
         [14],
         [15]],

        [[16],
         [17],
         [18]]],


       [[[19],
         [20],
         [21]],

        [[22],
         [23],
         [24]],

        [[25],
         [26],
         [27]]]], dtype=int32)

In [12]:
new_arr = arr * random_arr
new_arr

array([[[[  3,   1,   3],
         [ 18,  14,  18],
         [ 12,  21,  15]],

        [[ 32,  32,  32],
         [ 25,  40,  10],
         [ 36,  42,  18]],

        [[ 56,  21,  63],
         [ 64,  56,  40],
         [ 72,  36,  90]]],


       [[[ 30,  10,  30],
         [ 99,  77,  99],
         [ 48,  84,  60]],

        [[104, 104, 104],
         [ 70, 112,  28],
         [ 90, 105,  45]],

        [[128,  48, 144],
         [136, 119,  85],
         [144,  72, 180]]],


       [[[ 57,  19,  57],
         [180, 140, 180],
         [ 84, 147, 105]],

        [[176, 176, 176],
         [115, 184,  46],
         [144, 168,  72]],

        [[200,  75, 225],
         [208, 182, 130],
         [216, 108, 270]]]], dtype=int32)

In [13]:
@np.vectorize
def myfunc(a, b):
    if a > b:
        return a - b
    else:
        return a + b

In [14]:
myfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])