## Numpy Arrays vs Pyton Lists

1. **Python Lists**:
   - **Ordered and Changeable**: Lists are collections that maintain order and allow modifications (addition, removal, etc.).
   - **Heterogeneous**: Lists can hold different data types (e.g., strings, integers, floats).
   - **1-Dimensional by Default**: Although you can create N-dimensional lists, they are essentially 1-D lists storing other 1-D lists.
   - **Non-Contiguous Memory**: List elements need not be stored contiguously in memory.
   - **Overhead**: Lists store additional information about each element (type, reference count), which can impact memory usage.
   - **Performance**: Lists are not optimized for numerical computations and may be slower due to Python's interpretation overhead.

2. **NumPy Arrays**:
   - **Homogeneous and Typed**: NumPy arrays store homogenous, densely packed data (usually numbers) with a consistent data type.
   - **N-Dimensional Arrays**: You can create N-dimensional arrays using `numpy.array()`.
   - **Contiguous Memory**: Elements of a NumPy array are stored contiguously in memory.
   - **Efficient Mathematical Operations**: NumPy arrays facilitate efficient mathematical and other operations.
   - **Better for Numerical Data**: If you're working with numerical data and need high-performance computations, NumPy arrays are superior.


In [3]:
! pip install numpy

In [4]:
import numpy as np

In [6]:
sys_version = np.__version__
sys_version

'1.26.4'

### Why Numpy is Faster than Traditional Lists
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [18]:
list_array = [1,2,3]

In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [17]:
numpy_array_multiplication = a * 2
numpy_array_multiplication

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [19]:
list_array_multiplication = list_array * 2
list_array_multiplication

[1, 2, 3, 1, 2, 3]

In [9]:
a[0]

1

In [10]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [11]:
a[:3]

array([10,  2,  3])

In [12]:
b = a[3:]
b

array([4, 5, 6])

In [13]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
a[1, 3]

8

In [20]:
a.ndim

2

In [21]:
a.shape

(3, 4)

In [23]:
a.size

12