# Numpy Array Reshape Examples
### Reshaping 1D Arrays

Create a 1D array with 12 elements and reshape it:
- Creating a 1D array. 
- Reshaping to a 2D array (3x4). 
- Reshaping to a 2D array (4x3). 
- Reshaping to a 3D array (2x3x2). 
- Flattening the 3D array back to 1D. 

In [2]:
! pip install numpy

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr = arr.reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
arr = arr.reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
arr = arr.reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [11]:
arr = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Create a 1D array 
- Reshape to a 2x3x4 array.
- Reshape to a 2x5x3 array, then reshape it back to a 5x6 array.

Create a 1D array with values from 0 to 23. Reshape it to a 3D array with dimensions (2, 3, 4).

Concatenate two 1D arrays of size 10, reshape the resulting array to a 2D array with dimensions (2, 10).

Split a 1D array of values from 0 to 29 into three equal parts and reshape each part to a 2D array with dimensions (2, 5).

In [12]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
arr = arr.reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
arr = np.arange(30).reshape(2,5,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [15]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)

In [17]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
arr = np.concatenate((arr1, arr2))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
arr = arr.reshape(2,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [36]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
arrs = np.array_split(arr, 3)
for arr in arrs:
    print(arr.reshape(2,5))


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]]


### Reshaping 2D Arrays

Create a 2D array filled with random numbers, reshape it into a (3, 8) array, then reshape it back into a 1D array.

Create a 2D array of shape (4, 4), reshape it into (2, -1). The resulting array shape.

In [38]:
arr = np.random.randint(0, 1000, size=(3,8))
arr

array([[190, 464, 599, 740, 869, 809, 431, 359],
       [689, 776, 339, 548,  78, 817, 713, 301],
       [657,  61, 931, 854, 195, 161, 251, 289]])

In [39]:
arr = arr.flatten()
arr

array([190, 464, 599, 740, 869, 809, 431, 359, 689, 776, 339, 548,  78,
       817, 713, 301, 657,  61, 931, 854, 195, 161, 251, 289])

In [40]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
arr = arr.reshape(2,-1)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])


### Reshaping 3D Arrays

Create a 1D array and reshape it to:
- A 3D array of shape (2, 3, 4).
- A 3D array of shape (5, 2, 3).

Create a 3D array and reshape it to:
- A 2D array of shape (6, 4).
- A 2D array of shape (12, 5).
- A 2D array with 5 rows.

Create a 3D array and flatten it into a 1D array.

In [43]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
arr = np.arange(30).reshape(5,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [47]:
arr = np.random.rand(6,2,2)
arr

array([[[0.35895066, 0.66493924],
        [0.57393802, 0.34928858]],

       [[0.98023415, 0.70528106],
        [0.56742422, 0.02066462]],

       [[0.87604546, 0.82126013],
        [0.41793928, 0.61223309]],

       [[0.42843654, 0.8786007 ],
        [0.6689434 , 0.72864744]],

       [[0.75407859, 0.15751332],
        [0.81008281, 0.61164667]],

       [[0.44878524, 0.37436424],
        [0.63704533, 0.01126652]]])

In [48]:
arr = arr.reshape(6,4)
arr

array([[0.35895066, 0.66493924, 0.57393802, 0.34928858],
       [0.98023415, 0.70528106, 0.56742422, 0.02066462],
       [0.87604546, 0.82126013, 0.41793928, 0.61223309],
       [0.42843654, 0.8786007 , 0.6689434 , 0.72864744],
       [0.75407859, 0.15751332, 0.81008281, 0.61164667],
       [0.44878524, 0.37436424, 0.63704533, 0.01126652]])

In [49]:
arr = np.random.rand(5,4,3)
arr

array([[[0.61333655, 0.96698824, 0.06315387],
        [0.55107459, 0.99122453, 0.83629643],
        [0.13374463, 0.65899113, 0.72633362],
        [0.62256192, 0.55496276, 0.27148355]],

       [[0.19686851, 0.51634221, 0.93236657],
        [0.41725054, 0.60325038, 0.62762341],
        [0.63620165, 0.04857112, 0.11236729],
        [0.00414915, 0.47565955, 0.03857628]],

       [[0.22109776, 0.9620726 , 0.03475315],
        [0.88820517, 0.51635598, 0.8793097 ],
        [0.01088746, 0.91388557, 0.12343163],
        [0.10197666, 0.25189764, 0.31859173]],

       [[0.62174237, 0.9618483 , 0.11502687],
        [0.09216873, 0.35475559, 0.63008821],
        [0.47148465, 0.85852746, 0.32840182],
        [0.51428811, 0.85559928, 0.17786895]],

       [[0.5302555 , 0.30684385, 0.90236811],
        [0.74865773, 0.60231152, 0.74808203],
        [0.86519142, 0.40465448, 0.18867201],
        [0.29887163, 0.35011127, 0.52426983]]])

In [50]:
arr = arr.reshape(12,5)
arr

array([[0.61333655, 0.96698824, 0.06315387, 0.55107459, 0.99122453],
       [0.83629643, 0.13374463, 0.65899113, 0.72633362, 0.62256192],
       [0.55496276, 0.27148355, 0.19686851, 0.51634221, 0.93236657],
       [0.41725054, 0.60325038, 0.62762341, 0.63620165, 0.04857112],
       [0.11236729, 0.00414915, 0.47565955, 0.03857628, 0.22109776],
       [0.9620726 , 0.03475315, 0.88820517, 0.51635598, 0.8793097 ],
       [0.01088746, 0.91388557, 0.12343163, 0.10197666, 0.25189764],
       [0.31859173, 0.62174237, 0.9618483 , 0.11502687, 0.09216873],
       [0.35475559, 0.63008821, 0.47148465, 0.85852746, 0.32840182],
       [0.51428811, 0.85559928, 0.17786895, 0.5302555 , 0.30684385],
       [0.90236811, 0.74865773, 0.60231152, 0.74808203, 0.86519142],
       [0.40465448, 0.18867201, 0.29887163, 0.35011127, 0.52426983]])

In [51]:
arr = arr.reshape(5,12)
arr

array([[0.61333655, 0.96698824, 0.06315387, 0.55107459, 0.99122453,
        0.83629643, 0.13374463, 0.65899113, 0.72633362, 0.62256192,
        0.55496276, 0.27148355],
       [0.19686851, 0.51634221, 0.93236657, 0.41725054, 0.60325038,
        0.62762341, 0.63620165, 0.04857112, 0.11236729, 0.00414915,
        0.47565955, 0.03857628],
       [0.22109776, 0.9620726 , 0.03475315, 0.88820517, 0.51635598,
        0.8793097 , 0.01088746, 0.91388557, 0.12343163, 0.10197666,
        0.25189764, 0.31859173],
       [0.62174237, 0.9618483 , 0.11502687, 0.09216873, 0.35475559,
        0.63008821, 0.47148465, 0.85852746, 0.32840182, 0.51428811,
        0.85559928, 0.17786895],
       [0.5302555 , 0.30684385, 0.90236811, 0.74865773, 0.60231152,
        0.74808203, 0.86519142, 0.40465448, 0.18867201, 0.29887163,
        0.35011127, 0.52426983]])

In [52]:
arr = arr.reshape(5,4,3)
arr

array([[[0.61333655, 0.96698824, 0.06315387],
        [0.55107459, 0.99122453, 0.83629643],
        [0.13374463, 0.65899113, 0.72633362],
        [0.62256192, 0.55496276, 0.27148355]],

       [[0.19686851, 0.51634221, 0.93236657],
        [0.41725054, 0.60325038, 0.62762341],
        [0.63620165, 0.04857112, 0.11236729],
        [0.00414915, 0.47565955, 0.03857628]],

       [[0.22109776, 0.9620726 , 0.03475315],
        [0.88820517, 0.51635598, 0.8793097 ],
        [0.01088746, 0.91388557, 0.12343163],
        [0.10197666, 0.25189764, 0.31859173]],

       [[0.62174237, 0.9618483 , 0.11502687],
        [0.09216873, 0.35475559, 0.63008821],
        [0.47148465, 0.85852746, 0.32840182],
        [0.51428811, 0.85559928, 0.17786895]],

       [[0.5302555 , 0.30684385, 0.90236811],
        [0.74865773, 0.60231152, 0.74808203],
        [0.86519142, 0.40465448, 0.18867201],
        [0.29887163, 0.35011127, 0.52426983]]])

In [53]:
arr = arr.flatten()
arr

array([0.61333655, 0.96698824, 0.06315387, 0.55107459, 0.99122453,
       0.83629643, 0.13374463, 0.65899113, 0.72633362, 0.62256192,
       0.55496276, 0.27148355, 0.19686851, 0.51634221, 0.93236657,
       0.41725054, 0.60325038, 0.62762341, 0.63620165, 0.04857112,
       0.11236729, 0.00414915, 0.47565955, 0.03857628, 0.22109776,
       0.9620726 , 0.03475315, 0.88820517, 0.51635598, 0.8793097 ,
       0.01088746, 0.91388557, 0.12343163, 0.10197666, 0.25189764,
       0.31859173, 0.62174237, 0.9618483 , 0.11502687, 0.09216873,
       0.35475559, 0.63008821, 0.47148465, 0.85852746, 0.32840182,
       0.51428811, 0.85559928, 0.17786895, 0.5302555 , 0.30684385,
       0.90236811, 0.74865773, 0.60231152, 0.74808203, 0.86519142,
       0.40465448, 0.18867201, 0.29887163, 0.35011127, 0.52426983])

### Advanced Reshaping

Create a 3D array of shape (4, 3, 2) and reshape it into a 2D array with 6 rows.

Create a 1D array, reshape it to a 3D array of shape (3, 4, 5), then to a 2D array of shape (15, 4).

Create a 3D array, flatten it to a 1D array, reshape it to a 2D array of shape (4, 6), and finally reshape it back to a 3D array of shape (2, 6, 2).

Create a 1D array and reshape it into a 2D array of shape (4, 5). Flatten it, then reshape it into a 3D array of shape (2, 2, 5).

Create a 3D array with shape (3, 3, 3), fill it with random integers, reshape it into a 2D array, and sort all elements in ascending order.


In [54]:
arr = np.random.rand(4,3,2).reshape(6,4)
arr

array([[0.01774377, 0.19981173, 0.51275759, 0.89987522],
       [0.5294151 , 0.81495685, 0.49435494, 0.55253907],
       [0.50891587, 0.31568739, 0.3842508 , 0.74936261],
       [0.26482889, 0.41834363, 0.59409573, 0.03704491],
       [0.90564334, 0.67680351, 0.15745785, 0.05664714],
       [0.08310796, 0.59880609, 0.96977341, 0.26304296]])

In [56]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [57]:
arr = arr.reshape(3,4,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [58]:
arr = arr.reshape(15,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [60]:
arr = np.arange(24).reshape(6,2,2)
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [61]:
arr = arr.reshape(4,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [62]:
arr = arr.reshape(2,6,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [63]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
arr = arr.reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
arr = arr.reshape(2,2,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [68]:
arr = np.random.randint(20, size=(3,3,3))
arr

array([[[19,  2, 19],
        [ 3, 16,  0],
        [14,  7, 13]],

       [[ 7, 11, 10],
        [16,  9,  3],
        [ 0, 18,  3]],

       [[ 7, 19, 17],
        [ 7, 18, 14],
        [12,  6,  6]]])

In [69]:
arr = arr.reshape(9,3)
arr

array([[19,  2, 19],
       [ 3, 16,  0],
       [14,  7, 13],
       [ 7, 11, 10],
       [16,  9,  3],
       [ 0, 18,  3],
       [ 7, 19, 17],
       [ 7, 18, 14],
       [12,  6,  6]])