In [2]:
! pip install numpy

In [3]:
import numpy as np

# Numpy Data Type Practice

- Create a 1D array of integers from 1 to 5 with data type int32.

- Create a 2D array of shape (3, 3) with data type float64 where all elements are zero.

- Create a 3D array of shape (2, 2, 2) with random integers between 0 and 100 with data type int8.

- Convert a 1D array of integers to an array of floats.

- Create a 2D array of shape (2, 3) with data type float32 and then convert it to int32.


In [4]:
arr = np.arange(1,6,dtype=np.int32)
arr

array([1, 2, 3, 4, 5], dtype=int32)

In [5]:
arr = np.zeros((3, 3), dtype=np.float64)
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr = np.random.randint(0, 100, size=(2, 2, 2), dtype=np.int8)
arr

array([[[83, 76],
        [69, 38]],

       [[67, 26],
        [93, 27]]], dtype=int8)

In [7]:
arr_int = np.zeros((2,2),dtype=np.int8)
arr_int

array([[0, 0],
       [0, 0]], dtype=int8)

In [8]:
arr_float = arr_int.astype(np.float32)
arr_float

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [9]:
arr_float32 = np.array([[1.87, 2.9, 3.07], [4.5, 5.3, 6.06]], dtype=np.float32)
arr_int32 = arr_float32.astype(np.int32)
arr_int32


array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# Numpy 3-D Array Practice
- Create a 3D array of shape (4, 3, 2) with all elements initialized to zero.

- Create a 3D array of shape (2, 5, 4) with all elements initialized to one.

- Create a 3D array of shape (3, 3, 3) with random integers between 10 and 20.

In [10]:
arr = np.zeros((4, 3, 2))
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
arr = np.ones((2, 5, 4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
arr = np.random.randint(10, 20, size=(3,3,3), dtype=np.int32)
arr

array([[[14, 11, 18],
        [15, 18, 17],
        [11, 19, 10]],

       [[10, 14, 17],
        [16, 15, 11],
        [19, 19, 10]],

       [[10, 11, 16],
        [11, 12, 18],
        [18, 17, 18]]], dtype=int32)

1. Create a 3D array of dimensions 3x3x3 with all elements initialized to zero.

   ```python
   array_3d = np.zeros((3, 3, 3), dtype=int)
   ```

   Optionally, initialize with some values for practice:

   ```python
   array_3d = np.array([[[ 1,  2,  3], [ 4,  5,  6], [ 7,  8,  9]],
                        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                        [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
   ```

   Iterate over all elements in the 3D array.

In [13]:
array_3d = np.zeros((3, 3, 3), dtype=int)
array_3d = np.array([[[ 1,  2,  3], [ 4,  5,  6], [ 7,  8,  9]],
                        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                        [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [14]:
for i in range(3):
    for j in range(3):
        for k in range(3):
            print(array_3d[i][j][k], end=' ')
        print(" ")
    print(" ")

1 2 3  
4 5 6  
7 8 9  
 
10 11 12  
13 14 15  
16 17 18  
 
19 20 21  
22 23 24  
25 26 27  
 


2. Create a 3D array of shape (3, 4, 5) filled with random integers between 0 and 20, and print the array.

   - Access and print the element at position (2, 3, 4) in the 3D array created above.

   - Access and print the entire first row of the second matrix (i.e., when the first-dimension index is 1).

   - Add 5 to each element in the 3D array and print the result.

   - Multiply each element in the 3D array by 2 and print the result.

   - Calculate and print the sum of all elements in the 3D array.

   - Calculate and print the mean of the elements along the second axis.

   - Create a new array containing only the elements from the original 3D array that are greater than 10.

   - Replace all elements in the 3D array that are less than 10 with the value 0 and print the modified array.

In [15]:
arr = np.random.randint(0, 20, size=(3, 4, 5), dtype=np.int32)
arr

array([[[ 7, 15,  2, 15,  4],
        [10,  7,  1, 19, 12],
        [15, 18, 17, 15, 10],
        [14, 19,  5,  2, 12]],

       [[ 9,  8,  4,  7,  8],
        [19, 12,  8, 15, 19],
        [ 6,  4, 15,  3,  5],
        [14, 16,  9, 15, 11]],

       [[19, 16, 15,  5, 14],
        [17, 12, 14, 12, 13],
        [ 5,  7, 18,  7,  4],
        [ 1, 12,  7, 19, 13]]], dtype=int32)

In [17]:
arr[2, 3, 4]

np.int32(13)

In [19]:
arr[1,0]

array([9, 8, 4, 7, 8], dtype=int32)

In [22]:
arr_add = arr + 5
arr_add

array([[[17, 25, 12, 25, 14],
        [20, 17, 11, 29, 22],
        [25, 28, 27, 25, 20],
        [24, 29, 15, 12, 22]],

       [[19, 18, 14, 17, 18],
        [29, 22, 18, 25, 29],
        [16, 14, 25, 13, 15],
        [24, 26, 19, 25, 21]],

       [[29, 26, 25, 15, 24],
        [27, 22, 24, 22, 23],
        [15, 17, 28, 17, 14],
        [11, 22, 17, 29, 23]]], dtype=int32)

In [23]:
arr_mul = arr * 2
arr_mul

array([[[24, 40, 14, 40, 18],
        [30, 24, 12, 48, 34],
        [40, 46, 44, 40, 30],
        [38, 48, 20, 14, 34]],

       [[28, 26, 18, 24, 26],
        [48, 34, 26, 40, 48],
        [22, 18, 40, 16, 20],
        [38, 42, 28, 40, 32]],

       [[48, 42, 40, 20, 38],
        [44, 34, 38, 34, 36],
        [20, 24, 46, 24, 18],
        [12, 34, 24, 48, 36]]], dtype=int32)

In [24]:
np.sum(arr)

np.int64(956)

In [30]:
print(arr.mean(axis=1))

[[16.5  19.75 11.25 17.75 14.5 ]
 [17.   15.   14.   15.   15.75]
 [15.5  16.75 18.5  15.75 16.  ]]


In [29]:
new_array = arr[arr > 10]
new_array

array([12, 20, 20, 15, 12, 24, 17, 20, 23, 22, 20, 15, 19, 24, 17, 14, 13,
       12, 13, 24, 17, 13, 20, 24, 11, 20, 19, 21, 14, 20, 16, 24, 21, 20,
       19, 22, 17, 19, 17, 18, 12, 23, 12, 17, 12, 24, 18], dtype=int32)

In [32]:
arr[arr < 10] = 0
arr

array([[[12, 20,  0, 20,  0],
        [15, 12,  0, 24, 17],
        [20, 23, 22, 20, 15],
        [19, 24, 10,  0, 17]],

       [[14, 13,  0, 12, 13],
        [24, 17, 13, 20, 24],
        [11,  0, 20,  0, 10],
        [19, 21, 14, 20, 16]],

       [[24, 21, 20, 10, 19],
        [22, 17, 19, 17, 18],
        [10, 12, 23, 12,  0],
        [ 0, 17, 12, 24, 18]]], dtype=int32)