In [3]:
! pip install numpy

In [4]:
import numpy as np

In [20]:
arr = np.arange(1,11).reshape(5,2, order="F")
arr

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [15]:
arr = np.arange(1,11).reshape(5,2, order="C")
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
arr = np.arange(1,11).reshape(5,2, order="A")
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])