In [3]:
! pip install numpy

# 1-D Array Practice

**Basic Array Creation**

* Create a 1-dimensional array with the numbers from 0 to 9.
* Create a 1-dimensional array containing only even numbers from 10 to 20.
* Create a 1-dimensional array with 10 linearly spaced numbers between 0 and 1.

In [4]:
import numpy as np

In [5]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.arange(11,20,2)
arr

array([11, 13, 15, 17, 19])

In [7]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Array Calculations**

* Create a 1-dimensional array with numbers from 1 to 5 and calculate the square of each element.
* Create a 1-dimensional array with numbers from 1 to 5 and calculate the sum of all elements.
* Create a 1-dimensional array with numbers from 1 to 5 and calculate the cumulative sum of the elements.

In [8]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [9]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

In [10]:
np.sum(arr)

np.int64(15)

In [11]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

**Array Statistics**

* Create a 1-dimensional array with numbers from 1 to 10 and find the maximum and minimum values.
* Create a 1-dimensional array with numbers from 1 to 10 and find the mean and standard deviation.

In [12]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.max(arr)

np.int64(10)

In [14]:
np.min(arr)

np.int64(1)

In [15]:
np.mean(arr)

np.float64(5.5)

In [16]:
np.std(arr)

np.float64(2.8722813232690143)

**Array Manipulation**

* Create an integer array showcasing only those numbers that are divisible by 3.
* Create a null array of any length with the middle values as natural numbers.
* Take a 1D array (length >= 11) and negate all elements present between the 5th and 7th positions (inclusive of upper and lower bounds).
* Create a 1-D array of 50 evenly spaced elements between 35 and 140 (inclusive).

In [17]:
arr = np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
arr = np.zeros(10)
arr[4:6] = np.arange(1,3)
arr

array([0., 0., 0., 0., 1., 2., 0., 0., 0., 0.])

In [19]:
arr = np.arange(0,11)
arr[4:8] = -arr[4:8]
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [20]:
arr = np.linspace(35,140,50)
arr

array([ 35.        ,  37.14285714,  39.28571429,  41.42857143,
        43.57142857,  45.71428571,  47.85714286,  50.        ,
        52.14285714,  54.28571429,  56.42857143,  58.57142857,
        60.71428571,  62.85714286,  65.        ,  67.14285714,
        69.28571429,  71.42857143,  73.57142857,  75.71428571,
        77.85714286,  80.        ,  82.14285714,  84.28571429,
        86.42857143,  88.57142857,  90.71428571,  92.85714286,
        95.        ,  97.14285714,  99.28571429, 101.42857143,
       103.57142857, 105.71428571, 107.85714286, 110.        ,
       112.14285714, 114.28571429, 116.42857143, 118.57142857,
       120.71428571, 122.85714286, 125.        , 127.14285714,
       129.28571429, 131.42857143, 133.57142857, 135.71428571,
       137.85714286, 140.        ])

# Project: Analyzing Temperature Data

**Data Generation**

* Generate a 1-dimensional array of daily temperatures for 30 days.

In [21]:
daily_temps = np.random.randint(low=0, high=101, size=30)
daily_temps

array([24, 14, 56, 69,  9, 37, 39, 53, 44, 67, 97, 30, 52, 95, 51,  4,  4,
       63, 98, 87,  9,  0, 71, 60, 81, 42, 96, 65, 88, 88])

**Data Analysis**

* Find the average temperature for the month.
* Determine the hottest and coldest days of the month.
* Find the number of days the temperature was above the monthly average.

In [22]:
np.average(daily_temps)

np.float64(53.1)

In [23]:
hottest_day = daily_temps.max()
hottest_day

np.int64(98)

In [24]:
np.where(daily_temps == hottest_day)

(array([18]),)

In [25]:
coldest_day = daily_temps.min()
coldest_day

np.int64(0)

In [26]:

np.where(daily_temps == coldest_day)

(array([21]),)

In [27]:
np.mean(daily_temps)

np.float64(53.1)

In [28]:
above_avg_days = np.count_nonzero(daily_temps > np.mean(daily_temps))
above_avg_days

15

# Project: Analyzing Sales Data

**Data Generation**

* Create an array representing daily sales over 30 days, with sales numbers as random integers between 50 and 200.

In [29]:
sales = np.random.randint(50, 201, 30)
sales

array([193, 111,  84, 146, 144, 139, 143, 126, 133, 183,  55,  71, 180,
        90, 106,  91, 154, 172, 179,  66, 142,  75, 173,  68, 198, 112,
        80, 199,  82, 111])

**Sales Analysis**

* Compute total sales.
* Compute the average daily sales.
* Find the highest and lowest sales days.
* Compute a 7-day moving average of sales to identify trends.
* Identify days where sales were above the moving average.

In [30]:
total_sales = np.sum(sales)
total_sales

np.int64(3806)

In [31]:
avg_sales = np.average(sales)
avg_sales

np.float64(126.86666666666666)

In [32]:
np.where(sales == np.max(sales))

(array([27]),)

In [33]:
np.where(sales == np.min(sales))

(array([10]),)

In [34]:
week_size = 7
week_avg = []
i = 0
while i < len(sales)-6:
    val = np.mean(sales[i:i + week_size])
    week_avg.append(val)
    i += 1
week_avg

[np.float64(137.14285714285714),
 np.float64(127.57142857142857),
 np.float64(130.71428571428572),
 np.float64(144.85714285714286),
 np.float64(131.85714285714286),
 np.float64(121.42857142857143),
 np.float64(127.28571428571429),
 np.float64(119.71428571428571),
 np.float64(116.85714285714286),
 np.float64(110.85714285714286),
 np.float64(106.71428571428571),
 np.float64(123.42857142857143),
 np.float64(138.85714285714286),
 np.float64(122.57142857142857),
 np.float64(130.0),
 np.float64(125.57142857142857),
 np.float64(137.28571428571428),
 np.float64(125.0),
 np.float64(128.71428571428572),
 np.float64(119.14285714285714),
 np.float64(121.14285714285714),
 np.float64(129.28571428571428),
 np.float64(130.28571428571428),
 np.float64(121.42857142857143)]

# Project: Sales Data Analysis from CSV

**Data Import**

* Read the 'sales_data.csv' file using Python's CSV module and extract the sales data into a list.
* Convert the sales data list into a NumPy array.

In [110]:
import csv

In [111]:
with open('sales_data.csv', 'r', encoding='latin-1') as csvfile: 
    reader = csv.reader(csvfile)
    sales_data = list(reader)

sales_data_array = np.array(sales_data, dtype='float64')
sales_data_array

array([[18620., 88642., 11880., 33813., 38492., 61585., 13140., 93254.,
        87513., 18902., 42936., 50135.]])

**Sales Analysis**

* Calculate the total sales.
* Calculate the average sales.
* Find the maximum sales in a month.
* Find the minimum sales in a month.
* Identify months with sales above a certain threshold (e.g., 25000).

In [112]:
np.sum(sales_data_array)

np.float64(558912.0)

In [113]:
np.average(sales_data_array)

np.float64(46576.0)

In [114]:
np.max(sales_data_array)

np.float64(93254.0)

In [115]:
np.min(sales_data_array)

np.float64(11880.0)

In [118]:
temp, indexes = np.where(sales_data_array > 25000)
indexes

array([ 1,  3,  4,  5,  7,  8, 10, 11])